branches:
  only:
    - develop

image: Visual Studio 2022
configuration: Release
platform: Win32

build:
  project: src/RL-Mods.vcxproj
  parallel: false
  verbosity: minimal

artifacts:
  - path: 'src\Release\xinput1_3.dll'
    name: RL-Mods
